import * as React from 'react';
import type { InferGetStaticPropsType, NextPage } from 'next';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import ListItem from '../components/ListItem';
import { Joke } from '../types/Joke';
import { PopularityContext } from '../contexts/PopularityContext';
import { ActionType } from '../contexts/ActionTypes';
import uuid from 'react-uuid';
import ToggleSwitch from '../components/ToggleSwitch';

export const getStaticProps: GetStaticProps = async (): Promise<{ props: { jokes: Joke[] } }> => {
  const res = await fetch('https://joke.deno.dev/10');
  const jokes: Joke[] = await res.json();

  return {
    props: {
      jokes,
    },
  };
};

const List: NextPage = ({ jokes }: InferGetStaticPropsType<typeof getStaticProps>) => {
  const [showLiked, setShowLiked] = React.useState<boolean>(false);
  const { state, dispatch } = React.useContext(PopularityContext);

  React.useEffect(() => {
    dispatch
      ? dispatch({
          type: ActionType.SET_DEFAULT_LIST,
          payload: {
            defaultList: jokes,
          },
        })
      : null;
  }, [dispatch, jokes]);

  return (
    <div>
      <Head>
        <title>Orion Interview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-1 justify-items-center content-center">
        <div className="grid grid-cols-1 justify-items-center content-center max-w-5xl">
          <h1 className="text-5xl text-green-pastel font-sans font-medium mt-10">Humor is when you ask...</h1>
          <ToggleSwitch toggle={showLiked} setToggle={setShowLiked} />
          <div className="max-w-lg mt-5">
            {!showLiked
              ? state?.defaultList.map((joke: Joke) => <ListItem joke={joke} key={uuid()} />)
              : state?.likedJokes.map((joke: Joke) => <ListItem joke={joke} key={uuid()} />)}
          </div>
        </div>
      </main>
    </div>
  );
};

export default List;
